app_legacy:
    resource: .
    type: legacy

_core_controller:
    resource: '../classes/Controllers'
    type:     annotation
    prefix:   /

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler