security:
    encoders:
        App\Models\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: legacy_users
            anonymous: true
            lazy: true
            form_login:
                username_parameter: username
                password_parameter: password
                login_path: app_login
                check_path: app_login
                default_target_path: /
            logout:
                path: app_logout

    providers:
        legacy_users:
            id: app.security.legacy_user_provider

    access_control:
        - { path: '^/admin', roles: ROLE_USER }