security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            form_login:
                username_parameter: username
                password_parameter: password
                login_path: /login
                check_path: /login
                default_target_path: /
            logout:
                path: /logout

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: keins, roles: [ 'ROLE_USER' ] }
                    admin: { password: keins, roles: [ 'ROLE_USER', 'ROLE_ADMIN' ] }

    access_control:
        - { path: '^/admin', roles: ROLE_USER }