services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../classes/*'
        exclude: '../classes/{Models,Exceptions,DependencyInjection}'

    App\Routing\:
        resource: '../classes/Routing/*'
        public: true

    App\Routing\RouteLoader:
        tags: [routing.loader]

    App\Controllers\:
        resource: '../classes/Controllers/'
        public: true

    app.security.legacy_user_provider:
        class: App\Security\UserProvider

    app.twig.loader:
        class: Twig\Loader\FilesystemLoader
        arguments:
            $paths: '%kernel.project_dir%/src/views/'

