services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../classes/*'

    App\Routing\:
        resource: '../classes/Routing/*'
        public: true

    App\Routing\RouteLoader:
        tags: [routing.loader]

    App\Controllers\:
        resource: '../classes/Controllers/'
        public: true
